import Footer from "@/components/Shared/Footer";
import Navbar from "@/components/Shared/Navbar";
import "./globals.css";

export const metadata = {
  title: "Next Js App Route",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
